### ISSUE TITLE
I need CRC check

### ISSUE THREAD

**Issue by hyuckkim** [FRex/analyzepng#1]
Each chunks of png file include a four-byte cycle redundency check (CRC). If image miss make CRC to right value, browser cannot read image on online. 
https://www.w3.org/TR/2003/REC-PNG-20031110/#5Chunk-layout

Your tool is very useful and I fix error by your tool. I guess CRC check is useful. 

I think you can try this code. 
https://stackoverflow.com/questions/24082305/how-is-png-crc-calculated-exactly

**Comment by FRex** [comment]
This is on my TODO list.
I will add a `--crc` option tomorrow.

**Comment by FRex** [comment]
Okay, a `--crc` option was added. README has an example and there is new release exe too.
